#!/bin/bash
# OpenClaw One-Line Installer for Ubuntu VPS
# Repository: https://github.com/wheeldaemon/OpenClawChatBot
# Ключи запрашиваются ТОЛЬКО здесь, при установке!

set -e

echo "=========================================="
echo "    OpenClaw Interactive Installer"
echo "    GitHub: wheeldaemon/OpenClawChatBot"
echo "=========================================="
echo ""

# Проверка root (не обязательно, но удобно)
if [ "$EUID" -eq 0 ]; then 
   echo "Запуск от root обнаружен..."
fi

# Установка зависимостей если нужно
install_deps() {
    echo "Проверка зависимостей..."
    
    if ! command -v git &> /dev/null; then
        echo "Установка Git..."
        apt-get update && apt-get install -y git
    fi
    
    if ! command -v python3 &> /dev/null; then
        echo "Установка Python3..."
        apt-get update && apt-get install -y python3 python3-venv python3-pip
    fi
}

# === ИНТЕРАКТИВНЫЙ ВВОД ДАННЫХ (ТОЛЬКО ПРИ УСТАНОВКЕ) ===
echo ""
echo "Введи данные для конфигурации OpenClaw:"
echo ""

read -p "OpenRouter API Key: " api_key
read -p "Название модели (например: qwen/qwen-2.5-72b-instruct): " model_name
read -p "Telegram Bot ID: " telegram_bot_id
read -p "Telegram User ID: " telegram_user_id

echo ""
echo "Устанавливаю зависимости..."
install_deps

# Клонирование этого репозитория
install_dir="$HOME/OpenClawChatBot"
repo_url="https://github.com/wheeldaemon/OpenClawChatBot"

echo ""
echo "Клонирую OpenClaw в $install_dir..."

if [ -d "$install_dir" ]; then
    rm -rf "$install_dir"
fi

git clone "$repo_url" "$install_dir"
cd "$install_dir"

# Создание .env файла с введёнными данными
cat > .env << EOF
# OpenClaw Configuration
# Auto-generated by installer

OPENROUTER_API_KEY=$api_key
OPENROUTER_MODEL=$model_name
TELEGRAM_BOT_ID=$telegram_bot_id
TELEGRAM_USER_ID=$telegram_user_id
LOG_LEVEL=INFO
EOF

chmod 600 .env

# Создание виртуального окружения
echo "Создаю Python виртуальное окружение..."
python3 -m venv venv

# Установка зависимостей
echo "Устанавливаю Python зависимости..."
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

echo ""
echo "=========================================="
echo "    Установка завершена успешно!"
echo "=========================================="
echo ""
echo "Конфигурация сохранена в: $install_dir/.env"
echo ""
echo "Для запуска бота:"
echo "  cd $install_dir"
echo "  source venv/bin/activate"
echo "  python bot.py"
echo ""
echo "Для фонового запуска (screen):"
echo "  screen -S openclaw"
echo "  source venv/bin/activate && python bot.py"
echo ""
echo "Для автозапуска через systemd:"
echo "  sudo nano /etc/systemd/system/openclaw.service"
echo ""
echo "Содержимое для сервиса:"
echo "[Unit]"
echo "Description=OpenClaw Telegram Bot"
echo "After=network.target"
echo ""
echo "[Service]"
echo "Type=simple"
echo "User=$USER"
echo "WorkingDirectory=$install_dir"
echo "Environment=PATH=$install_dir/venv/bin"
echo "ExecStart=$install_dir/venv/bin/python $install_dir/bot.py"
echo "Restart=always"
echo "RestartSec=10"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo ""
echo "Затем:"
echo "  sudo systemctl daemon-reload"
echo "  sudo systemctl enable openclaw"
echo "  sudo systemctl start openclaw"
